export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git bun zsh-autosuggestions zsh-syntax-highlighting)
source "$ZSH/oh-my-zsh.sh"

eval "$(direnv hook zsh)"

if [ -f $HOME/.zshrc_local ]; then
  source "$HOME/.zshrc_local"
fi
